### ISSUE TITLE
Adding Refresh Tokens to the up_JWT & mp_JWT

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#64]
#### Description
Currently there are no way to renew the expiry dates on any of the JWTs we are using (currently set a 7 days!). 
The only way to renew is to do a full refresh of the tunnel.
 
This poses a security risk! 

The goal of this Issue is to create the API endpoint on proxy + the necessary functions in the interceptor and middleware to refresh the two tokens.

#### Acceptance Criteria
(@stravid87)

```[tasklist]
### Tasks
- [ ] Added short expiry time for the current upJWT and mpJWT Tokens (currently it is 7 days)
- [ ] Make an endpoint in the layer8 proxy to be used by the interceptor for TOKENs refresh
- [ ] Upon expiry of TOKENs, both of the JWT's should be refreshed automatically without getting the user notified about any error or anything
```

**Comment by huzaifamk** [comment]
Implemented long ago by me, marking as done.
