### ISSUE TITLE
Integrate Layer8 Payments With Web3.0

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#68]
## Overview
The clients of Layer8 will be using crypto to pay for our services. When a client logs in, they will see their usage statistics displayed for them to see. This usage is convertible to a fee that must be paid in crypto. 

## Notes
1) I do NOT want to integrate "Sign In With Ethereum." Instead we will keep the web2.0 sign in flow.
2) For now Metamask will be assumed the wallet of choice. 
3) The amount of $$$ charged will be set low and does not need to be thought through from a business perspective.

### 1) 
As a client of Layer8
I want to pay my bill with money from my crypto wallet.
When I click the connect wallet button
I see that my wallet is connected and get the necessary prompts from Metamask to make this possible.

### 2)  
As a client of Layer8
I want to pay my bill with money from my crypto wallet.
When I click a "Pay Now" button
I see the correct amount of crypto get bundled into a transaction and sent to my wallet where I can click accept. My "total owing" is decreased by the amount paid once the transaction is accepted. 

```[tasklist]
### Tasks
- [x] Connect Metamask to Layer8
- [x] Calculate "Total Owing" using gathered statistics
- [x] Use the "Total Owing" to create a transaction for approval by Metamask
- [x] Connet the transaction to a "Pay Now" button.
- [x] Create a layer8 smart contract that will recieve payment
```

**Comment by stravid87** [comment]
@huzaifamk can you help me to review?

**Comment by stravid87** [comment]
Feb 8, 1-on-1
"Pay with crypto integrating with influx now"

**Comment by stravid87** [comment]
Planned: simple frontend improvements 
- transaction confirmation
- minor styling updates
